backend:
  build: backend/.
  command: python api.py
  ports:
    - "5000:5000"
  volumes:
    - backend/.:/back-end
  links:
    - db
  environment:
      - db=0.0.0.0
db:
  image: mongo:3.4.5

frontend:
  build: freelancerapp/.
  command: npm start
  ports:
    - "3000:3000"
  volumes:
    - freelancerapp/:/frontend